apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-miq6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0070-tenant/tkrw-pr712-0075-0070-app/devfile-sample-miq6@sha256:fe08dbb735d0e6c377c1ad5047f93a637bead8ac5a5ba8a6dde5df97d726f141
        name: my-nodejs
        resources: {}
status: {}
